### ISSUE TITLE
refactor git-ls-files into a common utils function

### ISSUE THREAD

**Issue by abulenok** [open-atmos/devops_tests#15]

**Comment by slayoo** [comment]
Currently, we do:
https://github.com/open-atmos/devops_tests/blob/269f8685a1973f8a788562ddbc918e6629017893/test_todos_annotated.py#L26
https://github.com/open-atmos/devops_tests/blob/269f8685a1973f8a788562ddbc918e6629017893/test_notebooks.py#L30

and there are still multiple instances where we use the old `findfiles`:
https://github.com/open-atmos/PySDM/blob/94d2c01441ccdcbf382c816e19a5441bbcaca666/tests/examples_tests/conftest.py#L77
https://github.com/open-atmos/PySDM/blob/94d2c01441ccdcbf382c816e19a5441bbcaca666/tests/examples_tests/test_tests_completeness.py#L11
